#!/bin/bash

# Import workspace into JupyterLab.
# jupyter lab workspaces import binder/workspace.json

jupyter nbextension enable --py --sys-prefix qgrid
jupyter labextension install \
    @jupyter-widgets/jupyterlab-manager \
    @jupyter-voila/jupyterlab-preview \
    jupyter-leaflet \
    qgrid2 
